### ISSUE TITLE
Features

### ISSUE THREAD

**Issue by krzysztof-magosa** [edestecd/puppet-macports#2]
Hi,

What about packages features?
For example I would like to install opencv with python27 support.
From command line I would need to run command:

```
sudo port install opencv +python27
```

Is that possible using this puppet module?

**Comment by edestecd** [comment]
Yes,  puppet provides a native package provider for macports.
https://docs.puppetlabs.com/references/latest/type.html#package-provider-macports

So you can do something like this:

``` puppet
package { 'opencv +python27':
  ensure   => installed,
  provider => macports,
  require  => Class['macports'], # to ensure macports is installed first
}
```

**Comment by edestecd** [comment]
It looks like variants may not supported like my example (although I'd try it first).
The doc from the link above says you need to make [the MacPorts variants.conf file](http://guide.macports.org/chunked/internals.configuration-files.html#internals.configuration-files.variants-conf), which you could probably manage with the `file` type.

**Comment by edestecd** [comment]
@krzysztof-magosa, does this solve your issue?

**Comment by krzysztof-magosa** [comment]
Hi @edestecd, using + in package name like in example doesn't work, I tried it before asking here.
However using variants.conf is good idea, I didn't know about this file earlier.
I think that it's good idea to just drop information about this into readme also.

Thanks, it solves issue.
